#!/bin/bash

# Note: This project is mainly for learning Lua, so I use this helper
# script to call the local Lua build as needed. (This is quite ugly
# and will be replaced at some point.)

# Usage example:
# ./run src/lua/generate-pdf.lua arg1

DIR="$(cd "$(dirname "$0")" && pwd)"
"$DIR/lua/bin/lua" "$@"
